version: '3.8'

services:
  bot:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - botnet

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: psychobot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - botnet

volumes:
  postgres_data:

networks:
  botnet:
    driver: bridge